blank_issues_enabled: false
contact_links:
   - name: Telegram  (television) channel
     url: https://t.me/moviepilot_channel
     about:  Update log
   - name: Telegram  Communication group
     url: https://t.me/moviepilot_official
     about:  Exchange and mutual aid
