name:  Item discussion
description: discussion
title: "[Discussion]: "
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        [BUG](https://github.com/jxxghp/MoviePilot-Frontend/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBUG%5D%3A)  Together with [Feature Request](https://github.com/jxxghp/MoviePilot-Frontend/issues/new?assignees=&labels=feature+request&template=feature_request.yml&title=%5BFeature+Request%5D%3A+)  Please go to the corresponding location to submit。
  - type: textarea
    id: discussion
    attributes:
      label:  Item discussion
      description:  Please describe in detail what needs to be discussed。
      placeholder: " Item discussion"
    validations:
      required: true
